### ISSUE TITLE
feed fzf-insert with text on the command line berfore the call

### ISSUE THREAD

**Issue by matclab** [shahinism/xontrib-fzf-widgets#6]
It would be very usefull to start fzf with `-q` and the text already on the command line.
It woul allow to type a part of the command and only after, calling fzf on the text already on the comand line (a sort of super completion)

**Comment by matclab** [comment]
Replacing 
```
choice = $(echo @(items) | @(selector) --tac  --tiebreak=index +m ).replace('\n', '')
```
with
```
choice = $(echo @(items) | @(selector) --tac  --tiebreak=index +m -q @(current_buffer.text)).replace('\n', '')
```

And using `current_buffer.text = command` after does the trick.

**Comment by shahinism** [comment]
@matclab Cool idea, would you mind to send a pull request?
